# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: string_concat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13string_concat.proto\"%\n\rStringRequest\x12\t\n\x01\x61\x18\x01 \x01(\t\x12\t\n\x01\x62\x18\x02 \x01(\t\" \n\x0eStringResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2@\n\x13StringConcatService\x12)\n\x06\x43oncat\x12\x0e.StringRequest\x1a\x0f.StringResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'string_concat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_STRINGREQUEST']._serialized_start=23
  _globals['_STRINGREQUEST']._serialized_end=60
  _globals['_STRINGRESPONSE']._serialized_start=62
  _globals['_STRINGRESPONSE']._serialized_end=94
  _globals['_STRINGCONCATSERVICE']._serialized_start=96
  _globals['_STRINGCONCATSERVICE']._serialized_end=160
# @@protoc_insertion_point(module_scope)
