# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import string_concat_pb2 as string__concat__pb2


class StringConcatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Concat = channel.unary_unary(
                '/StringConcatService/Concat',
                request_serializer=string__concat__pb2.StringRequest.SerializeToString,
                response_deserializer=string__concat__pb2.StringResponse.FromString,
                )


class StringConcatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Concat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StringConcatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Concat': grpc.unary_unary_rpc_method_handler(
                    servicer.Concat,
                    request_deserializer=string__concat__pb2.StringRequest.FromString,
                    response_serializer=string__concat__pb2.StringResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StringConcatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StringConcatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Concat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StringConcatService/Concat',
            string__concat__pb2.StringRequest.SerializeToString,
            string__concat__pb2.StringResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
