# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hyrch_serving.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hyrch_serving.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13hyrch_serving.proto\"6\n\rDetectRequest\x12\x11\n\tjson_data\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\"#\n\x0e\x44\x65tectResponse\x12\x11\n\tjson_data\x18\x01 \x01(\t\"&\n\x0fSetClassRequest\x12\x13\n\x0b\x63lass_names\x18\x01 \x03(\t\"\"\n\x10SetClassResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2:\n\x0bYoloService\x12+\n\x06\x44\x65tect\x12\x0e.DetectRequest\x1a\x0f.DetectResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hyrch_serving_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTREQUEST']._serialized_start=23
  _globals['_DETECTREQUEST']._serialized_end=77
  _globals['_DETECTRESPONSE']._serialized_start=79
  _globals['_DETECTRESPONSE']._serialized_end=114
  _globals['_SETCLASSREQUEST']._serialized_start=116
  _globals['_SETCLASSREQUEST']._serialized_end=154
  _globals['_SETCLASSRESPONSE']._serialized_start=156
  _globals['_SETCLASSRESPONSE']._serialized_end=190
  _globals['_YOLOSERVICE']._serialized_start=192
  _globals['_YOLOSERVICE']._serialized_end=250
# @@protoc_insertion_point(module_scope)
